### ISSUE TITLE
Error raised when using MySTRenderer from myst-demo and no CSS style

### ISSUE THREAD

**Issue by GYHHAHA** [executablebooks/myst-theme#43]
### Describe the bug

Here is the error

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'prototype')
    at sax.js:222:46
    at node_modules/sax/lib/sax.js (sax.js:1565:1)
    at __require (chunk-AC2VUBZ6.js?v=af094f58:11:50)
    at node_modules/xml-js/lib/xml2js.js (xml2js.js:1:11)
    at __require (chunk-AC2VUBZ6.js?v=af094f58:11:50)
    at node_modules/xml-js/lib/index.js (index.js:3:14)
    at __require (chunk-AC2VUBZ6.js?v=af094f58:11:50)
    at index.js:1:24
```

And also there is no CSS style in the web page for the component:

![23 03 2023_20 53 12_REC](https://user-images.githubusercontent.com/41546976/227404296-5dcf19e6-7324-4f4c-bd0f-e5fff6da219b.png)

I want to reproduce the sandbox example in a separate project, I'm not sure whether directly using the MySTRenderer from myst-demo will success. Since there is no formal docs for using it in React, please give some instructions on this.

Besides, I noticed that there is a editable component which is different from the sandbox in the myst docs. Is it still using the same component? If it's different from the above-mentioned MySTRenderer, how to reproduce this in react?

![23 03 2023_20 56 48_REC](https://user-images.githubusercontent.com/41546976/227404929-82138b1d-b548-4434-91dd-8c7474220875.png)

Thanks!

### Reproduce the bug

/

### List your environment

lastest

**Comment by GYHHAHA** [comment]
solved
